// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQiYKajwgoh3XfqmVyMzNEFDgYRlmVZ8',
    appId: '1:690501444152:web:eff4774e8f1385fedabccd',
    messagingSenderId: '690501444152',
    projectId: 'stocktracker-f8f91',
    authDomain: 'stocktracker-f8f91.firebaseapp.com',
    storageBucket: 'stocktracker-f8f91.firebasestorage.app',
    measurementId: 'G-D3CJ3QEXDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyGv8wKlYVLF-KkXBIlm1-Tb33MazV_w',
    appId: '1:690501444152:android:07e6cd21fa836e42dabccd',
    messagingSenderId: '690501444152',
    projectId: 'stocktracker-f8f91',
    storageBucket: 'stocktracker-f8f91.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUeRy2i9tQQIkVSuJ5da18pduHMP8wcCE',
    appId: '1:690501444152:ios:41236efe9719a140dabccd',
    messagingSenderId: '690501444152',
    projectId: 'stocktracker-f8f91',
    storageBucket: 'stocktracker-f8f91.firebasestorage.app',
    iosBundleId: 'com.example.stockTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUeRy2i9tQQIkVSuJ5da18pduHMP8wcCE',
    appId: '1:690501444152:ios:41236efe9719a140dabccd',
    messagingSenderId: '690501444152',
    projectId: 'stocktracker-f8f91',
    storageBucket: 'stocktracker-f8f91.firebasestorage.app',
    iosBundleId: 'com.example.stockTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtQiYKajwgoh3XfqmVyMzNEFDgYRlmVZ8',
    appId: '1:690501444152:web:d5a2a66fc421f47edabccd',
    messagingSenderId: '690501444152',
    projectId: 'stocktracker-f8f91',
    authDomain: 'stocktracker-f8f91.firebaseapp.com',
    storageBucket: 'stocktracker-f8f91.firebasestorage.app',
    measurementId: 'G-RKL8MZH1CZ',
  );
}
